# Generated by Django 3.1.2 on 2020-10-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('numberInStock', models.IntegerField(default=0)),
                ('dailyRentalRate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='movies.genre')),
            ],
        ),
    ]
