# Generated by Django 3.1.2 on 2020-10-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='_id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
