# Generated by Django 3.1.2 on 2020-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201009_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='_id',
            field=models.CharField(auto_created='g20201009011606', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='_id',
            field=models.CharField(auto_created='m20201009011606', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
