# Generated by Django 3.1.2 on 2020-10-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201009_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
